[package]
name = "forwarder_guest"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
forwarder = { path = "../../libs/libforwarder" }
poll_token_derive = "0.1.0"
remain = "0.2.14"
vmm-sys-util = "0.12.1"
